TOTAL_BYTES = 31

SEQUENCE_NUM_START = 0

SERVO_0_INDEX = 0       #pitch
SERVO_1_INDEX = 1       #roll
SERVO_2_INDEX = 2       # = 0
SERVO_3_INDEX = 3       # = 0

MOTOR_OFFSET  = 4

SPARE_0_INDEX = 5
SPARE_1_INDEX = 6
SPARE_2_INDEX = 7

SEQUENCE_NUM_END = 9

START_CHAR_0 = (0x13)
START_CHAR_1 = (0x37)

END_CHAR_0   = (0xBE)
END_CHAR_1   = (0xEF)

FIRST_DATA_BYTE =  2
LAST_DATA_BYTE  =  28

TOTA_DATA_BYTES =  27